# Generated by Django 2.1.4 on 2018-12-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppOne',
            new_name='App1',
        ),
    ]
