# Generated by Django 2.1.4 on 2018-12-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_app2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App2',
            new_name='class1',
        ),
        migrations.RenameModel(
            old_name='App1',
            new_name='class2',
        ),
        migrations.AlterModelTable(
            name='class1',
            table='_App1_class1',
        ),
        migrations.AlterModelTable(
            name='class2',
            table='_App1_class2',
        ),
    ]
