# Generated by Django 2.1.4 on 2018-12-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20181212_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='class3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
