# Generated by Django 2.1.4 on 2018-12-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_class3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='class1',
            new_name='class10',
        ),
        migrations.AlterModelTable(
            name='class10',
            table='_App1_class10',
        ),
    ]
