# Generated by Django 2.1.4 on 2019-04-12 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Application Admin'), (2, 'Service Provider'), (3, 'Family')], null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('daycareId', models.IntegerField(default=0)),
                ('parent_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mother'), (2, 'Father'), (3, 'Relative')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
