# Generated by Django 2.1.4 on 2019-04-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
