# Generated by Django 2.1.4 on 2019-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Application Admin'), (2, 'SERVICE PROVIDER'), (3, 'FAMILY')], null=True),
        ),
    ]
