# Generated by Django 2.1.4 on 2019-06-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='class10',
        ),
        migrations.DeleteModel(
            name='class2',
        ),
    ]
