# Generated by Django 2.1.4 on 2019-01-15 20:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('sandiego', django.db.models.manager.Manager()),
            ],
        ),
    ]
