# Generated by Django 2.1.4 on 2019-01-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190116_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='name',
        ),
    ]
