# Generated by Django 2.1.4 on 2019-01-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190110_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='category',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'Family'), (2, 'Facility')], default=0),
        ),
    ]
