# Generated by Django 2.1.4 on 2019-01-11 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_address_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityspace',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='householdmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
    ]
