# Generated by Django 2.1.4 on 2019-01-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190116_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='tesst',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
