# Generated by Django 2.1.4 on 2019-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190116_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityspace',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='householdmembershiptype',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
