# Generated by Django 2.1.4 on 2019-01-17 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_auto_20190116_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='address',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.AddField(
            model_name='consumer',
            name='primary_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='consumer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='base.Consumer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='license_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='ConsumerProfile',
        ),
    ]
