# Generated by Django 2.1.4 on 2019-01-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190117_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmembership',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='householdmembership',
            name='household',
        ),
        migrations.RemoveField(
            model_name='householdmembership',
            name='member',
        ),
        migrations.RemoveField(
            model_name='householdmembership',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='householdmembership',
            name='type',
        ),
        migrations.RemoveField(
            model_name='householdmembershiptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='householdmembershiptype',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='HouseholdMembership',
        ),
        migrations.DeleteModel(
            name='HouseholdMembershipType',
        ),
    ]
