# Generated by Django 2.1.4 on 2019-03-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_booknew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='booknew',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='booknew',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='householdmembershiptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='householdmembershiptype',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='householdmembership',
            name='type',
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='isChild',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Booknew',
        ),
        migrations.DeleteModel(
            name='HouseholdMembershipType',
        ),
    ]
