# Generated by Django 2.1.4 on 2019-03-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20190315_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={},
        ),
    ]
