# Generated by Django 2.1.4 on 2019-03-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20190315_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityspace',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Facility'),
        ),
    ]
