# Generated by Django 2.1.4 on 2019-03-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20190315_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityspace',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Facility'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Facility'),
        ),
    ]
