# Generated by Django 2.1.4 on 2019-03-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20190315_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmembership',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Household'),
        ),
    ]
