# Generated by Django 2.1.4 on 2019-04-12 20:01

import base.models.facility
import base.models.family
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20190315_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='client',
            field=models.OneToOneField(limit_choices_to=base.models.facility.Facility.limit_client_choices, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='base.Client'),
        ),
        migrations.AlterField(
            model_name='household',
            name='client',
            field=models.OneToOneField(limit_choices_to=base.models.family.Household.limit_client_choices, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='base.Client'),
        ),
        migrations.AlterField(
            model_name='householdmembership',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Household'),
        ),
    ]
