# Generated by Django 2.1.4 on 2019-04-16 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0025_auto_20190412_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model, object),
        ),
        migrations.CreateModel(
            name='ParentUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model, object),
        ),
        migrations.CreateModel(
            name='ProviderUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='provideruser_Creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='provideruser_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model, object),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='created_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='parentuser_Creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='modified_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='parentuser_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='created_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='adminuser_Creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='modified_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='adminuser_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
