# Generated by Django 2.1.4 on 2019-05-17 22:44

import base.models.facility
import base.models.family
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20190419_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '3. Addresses'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': '2. Clients'},
        ),
        migrations.AlterModelOptions(
            name='clienttype',
            options={'verbose_name_plural': '1 ClientType'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': '4. Facilities'},
        ),
        migrations.AlterModelOptions(
            name='facilityspace',
            options={'verbose_name_plural': '5. Facility Spaces'},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'verbose_name_plural': '7. Households'},
        ),
        migrations.AlterModelOptions(
            name='householdmembership',
            options={'verbose_name_plural': '8. Household Memberships'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '6. Facility Teacher'},
        ),
        migrations.AlterField(
            model_name='facility',
            name='client',
            field=models.OneToOneField(limit_choices_to=base.models.facility.Facility.limit_client_choices, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='clientFacility', serialize=False, to='base.Client'),
        ),
        migrations.AlterField(
            model_name='facilityspace',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitySpaces', to='base.Facility'),
        ),
        migrations.AlterField(
            model_name='household',
            name='client',
            field=models.OneToOneField(limit_choices_to=base.models.family.Household.limit_client_choices, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='clientHousehole', serialize=False, to='base.Client'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilityteachers', to='base.Facility'),
        ),
    ]
