# Generated by Django 2.1.4 on 2019-05-24 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0029_auto_20190517_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.ClientType'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('type', 'primary_user')},
        ),
    ]
