# Generated by Django 2.1.4 on 2019-06-09 02:27

import app_core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_core', '0002_facility_facilityspace_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('name', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(limit_choices_to=app_core.models.Household.limit_client_choices, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='clientHousehole', serialize=False, to='app_core.Client')),
                ('created_by', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='household_Creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '7. Households',
            },
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('isChild', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='householdmembership_Creator', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_core.Household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_core.Person')),
                ('modified_by', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='householdmembership_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '8. Household Memberships',
            },
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='household',
            name='member',
            field=models.ManyToManyField(through='app_core.HouseholdMembership', to='app_core.Person'),
        ),
        migrations.AddField(
            model_name='household',
            name='modified_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='household_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
