# Generated by Django 2.1.4 on 2018-12-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='UserProfiles',
        ),
    ]
