# Generated by Django 2.1.4 on 2018-12-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_auto_20181212_1732'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='auth_user_TTLProfile',
        ),
    ]
